from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Double,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    UniqueConstraint,
    func,
)

metadata = MetaData()

process_code_enum = Enum("PRESS", "BODY", "PAINT", "ASSEMBLY")
equipment_type_enum = Enum("HYDRAULIC_PRESS", "ROBOT_ARM", "CAMERA", "CONVEYOR")
source_type_enum = Enum("BOSCH", "FORD", "PRESS_CURRENT", "ROBOT_CURRENT", "THERMAL_VISION")
data_type_enum = Enum("PROCESS", "SENSOR", "QUALITY", "THERMAL")
quality_result_enum = Enum("NORMAL", "DEFECT")
expected_label_enum = Enum("NORMAL", "WARNING", "FAULT", "DEFECT")

car_master = Table(
    "car_master",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("vehicle_id", String(50), nullable=False),
    Column("car_type", String(20), nullable=False),
    Column("engine_type", String(30), nullable=False),
    Column("car_color", String(30), nullable=False),
    Column("fuel_efficiency", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False),
    UniqueConstraint("vehicle_id", name="uq_car_master_vehicle_id"),
)

equipment = Table(
    "equipment",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("process_code", process_code_enum, nullable=False),
    Column("equipment_code", String(50), nullable=False, unique=True),
    Column("equipment_name", String(100), nullable=False),
    Column("equipment_type", equipment_type_enum, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Index("idx_equipment_process_code", "process_code"),
)

manufacturing_event = Table(
    "manufacturing_event",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("car_master_id", BigInteger, ForeignKey("car_master.id")),
    Column("sample_manufacturing_event_id", String(50), nullable=False, unique=True),
    Column("equipment_code", String(50), ForeignKey("equipment.equipment_code")),
    Column("source_dataset", String(100)),
    Column("source_type", source_type_enum, nullable=False),
    Column("data_type", data_type_enum, nullable=False),
    Column("process_code", process_code_enum, nullable=False),
    Column("equipment_type", equipment_type_enum, nullable=False),
    Column("station_code", String(50)),
    Column("event_time", DateTime, nullable=False),
    Column("metric_code", String(50)),
    Column("metric_value", Double),
    Column("unit", String(20)),
    Column("process_time", Double),
    Column("waiting_time", Double),
    Column("quality_result", quality_result_enum),
    Column("defect_type", String(50)),
    Column("expected_is_abnormal", Boolean),
    Column("expected_abnormal_type", String(50)),
    Column("expected_severity", String(20)),
    Column("expected_label", expected_label_enum),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Index("idx_manufacturing_event_car_master_id", "car_master_id"),
    Index("idx_manufacturing_event_equipment_code", "equipment_code"),
    Index("idx_manufacturing_event_event_time", "event_time"),
)

manufacturing_event_json = Table(
    "manufacturing_event_json",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("event_id", String(100), nullable=False, unique=True),
    Column("event_time", DateTime, nullable=False),
    Column("car_master_id", BigInteger, ForeignKey("car_master.id"), nullable=False),
    Column("equipment_id", BigInteger, ForeignKey("equipment.id"), nullable=False),
    Column("process_code", process_code_enum, nullable=False),
    Column("station_code", String(50)),
    Column("equipment_code", String(50), nullable=False),
    Column("equipment_type", String(50)),
    Column("equipment_status", String(30)),
    Column("event_type", String(50)),
    Column("event_json", JSON, nullable=False),
    Column("is_sent", Boolean, nullable=False, server_default="0"),
    Column("sent_at", DateTime),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Index("idx_event_time_sent", "event_time", "is_sent"),
    Index("idx_process_time", "process_code", "event_time"),
    Index("idx_equipment_time", "equipment_code", "event_time"),
    Index("idx_car_time", "car_master_id", "event_time"),
    Index("idx_event_id", "event_id"),
    Index("idx_equipment_id_time", "equipment_id", "event_time"),
)

manufacturing_event_template = Table(
    "manufacturing_event_template",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("template_name", String(50), nullable=False),
    Column("template_event_id", String(100), nullable=False, unique=True),
    Column("event_offset_us", BigInteger, nullable=False),
    Column("car_master_id", BigInteger, ForeignKey("car_master.id"), nullable=False),
    Column("equipment_id", BigInteger, ForeignKey("equipment.id"), nullable=False),
    Column("process_code", process_code_enum, nullable=False),
    Column("station_code", String(50)),
    Column("equipment_code", String(50), nullable=False),
    Column("equipment_type", String(50)),
    Column("equipment_status", String(30)),
    Column("event_type", String(50)),
    Column("event_json", JSON, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint("template_name", "event_offset_us", name="uq_template_offset"),
    Index("idx_template_name_offset", "template_name", "event_offset_us"),
    Index("idx_template_process_offset", "template_name", "process_code", "event_offset_us"),
    Index("idx_template_equipment_offset", "template_name", "equipment_code", "event_offset_us"),
)

manufacturing_event_generation_job = Table(
    "manufacturing_event_generation_job",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("job_id", String(100), nullable=False, unique=True),
    Column("job_type", String(50), nullable=False),
    Column("status", String(30), nullable=False),
    Column("request_json", JSON, nullable=False),
    Column("result_json", JSON),
    Column("error_message", String(1000)),
    Column("total_expected_events", BigInteger, nullable=False, server_default="0"),
    Column("generated_count", BigInteger, nullable=False, server_default="0"),
    Column("affected_rows", BigInteger, nullable=False, server_default="0"),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("started_at", DateTime),
    Column("finished_at", DateTime),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Index("idx_generation_job_status_created", "status", "created_at"),
    Index("idx_generation_job_type_created", "job_type", "created_at"),
)

thermal_vision = Table(
    "thermal_vision",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("manufacturing_event_id", BigInteger, ForeignKey("manufacturing_event.id"), nullable=False),
    Column("car_master_id", BigInteger, ForeignKey("car_master.id")),
    Column("image_position", String(50)),
    Column("thermal_avg_temp", Double),
    Column("thermal_max_temp", Double),
    Column("thermal_min_temp", Double),
    Column("thermal_std_temp", Double),
    Column("thickness_value", Double),
    Column("defect_score", Double),
    Column("expected_vision_label", String(30)),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint("manufacturing_event_id", name="uq_thermal_vision_manufacturing_event_id"),
    Index("idx_thermal_vision_car_master_id", "car_master_id"),
)

robot_arm_vibration = Table(
    "robot_arm_vibration",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("manufacturing_event_id", BigInteger, ForeignKey("manufacturing_event.id"), nullable=False),
    Column("equipment_id", BigInteger, ForeignKey("equipment.id"), nullable=False),
    Column("measured_at", DateTime, nullable=False),
    Column("freq_0_100_hz", Float),
    Column("freq_101_200_hz", Float),
    Column("freq_201_300_hz", Float),
    Column("freq_301_400_hz", Float),
    Column("freq_401_500_hz", Float),
    Column("freq_501_600_hz", Float),
    Column("freq_601_700_hz", Float),
    Column("freq_701_800_hz", Float),
    Column("freq_801_900_hz", Float),
    Column("freq_901_1000_hz", Float),
    Column("freq_1001_1100_hz", Float),
    Column("freq_1101_1200_hz", Float),
    Column("freq_1201_1300_hz", Float),
    Column("freq_1301_1400_hz", Float),
    Column("freq_1401_1500_hz", Float),
    Column("freq_1501_1600_hz", Float),
    Index("idx_robot_arm_vibration_event_id", "manufacturing_event_id"),
    Index("idx_robot_arm_vibration_equipment_id", "equipment_id"),
    Index("idx_robot_arm_vibration_measured_at", "measured_at"),
)
